# Generated by Django 3.1.7 on 2021-04-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=1000)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('hospital_name', models.CharField(max_length=50)),
            ],
        ),
    ]
