# Generated by Django 3.1.7 on 2021-04-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210430_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
