# Generated by Django 3.1.7 on 2021-05-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='doctor/'),
        ),
    ]
