# Generated by Django 3.1.7 on 2021-05-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210509_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
