# Generated by Django 3.1.7 on 2021-04-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(max_length=1000)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
